- name: Installing dependencies
  shell: composer install --prefer-dist chdir={{ root_dir }}
  tags: demo

- name: chown project
  shell: chown {{ username }}:{{ username }} {{ root_dir }} -Rf
  tags: demo