- name: Installing composer dependencies
  composer: command=install working_dir={{ root_dir }} prefer_dist=yes no_dev=yes
  tags: demo

- name: Installing bower dependencies
  sudo: false
  shell: bower update -F chdir={{ root_dir }}
  tags: demo

- name: Chown project
  shell: chown {{ username }}:{{ username }} {{ root_dir }} -Rf
  tags: demo

- name: Create default tables
  shell: php {{ root_dir }}/apps/common/migrations/bootstrap.php
  tags: demoConta