- name: Installing dependencies
  shell: composer install --prefer-dist chdir={{ root_dir }}
  tags: demo

- name: Chown project
  shell: chown {{ username }}:{{ username }} {{ root_dir }} -Rf
  tags: demo

- name: Create default tables
  shell: php {{ root_dir }}/apps/common/migrations/bootstrap.php
  tags: demo